### ISSUE TITLE
[Room States

### ISSUE THREAD

**Issue by TMGWill** [Berea-CS-Courses/capstone-project-TMGWill#15]
I need to implement a way for different rooms to have certain states to be able to manipulate the rooms for efficiently.

**Comment by jazzij** [comment]
I think you're on the right track with using room states to hold the type of room. What might be useful also is for you to create a map of your rooms (use graph paper or [online graph paper software](https://print-graph-paper.com/virtual-graph-paper)) so that you have a clear idea where everything is and how it all fits in your story. If you write everything out like this, it will be easier to see how common shared features of the room can be encoded as states rather than written out individually. This will make it much easier and faster to develop your game, debug it if you run into any problems, and expand it if you wish.
